### PR TITLE
Update node version in GH Actions

### PR DESCRIPTION
**Pull request by kacperpONS**
# Motivation and Context

Node.js 16 actions are being deprecated, we need to update.

# What has changed

Updated Node.js version for GitHub Actions.

# How to test?

See the relevant commits in the action's repos and check that our versions match:

- [actions/checkout](https://github.com/actions/checkout/commit/97a652b80035363df47baee5031ec8670b8878ac)
- [google-github-actions/auth](https://github.com/google-github-actions/auth/commit/43a59886fcb7545b65158bdc879d7b29e7f3ab05)
- [docker/login-action](https://github.com/docker/login-action/commit/3c2fe176ab3489635dda352c921ddbb8fb14b254)
- [actions/setup-java](https://github.com/actions/setup-java/commit/387ac29b308b003ca37ba93a6cab5eb57c8f5f93)
- [codecov/codecov-action](https://github.com/codecov/codecov-action/commit/0cf8684c821546a4e0c8c9a4cf4f21a7a0c5014b)
- [actions/setup-node](https://github.com/actions/setup-node/commit/54534a2a9ba7308e8a8995af3104899e6a95b681)

# Links

https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=2913&view=detail&selectedIssue=SDCSRM-374
https://trello.com/c/9Ey1O101/1388-upgrade-github-actions-version-5

# Screenshots (if appropriate):

### CODE REVIEW

**Review by AdamHawtin — CHANGES_REQUESTED** [review]
I don't think this what the card was referring to, it is the actual actions themselves built on Node 16 which are being deprecated. So long as we're using all the action versions listed as running on Node 20, we're fine as far as the actions go.

Since Node 16 is EOL, we do need to look at upgrading everywhere we use it in our code, but I think that's a bigger job outside the scope of this ticket, and until we've done that we should keep the Node version we run the checks with at 16 hear, since that's what we're currently actually building with. I will add a card to look at the wider job of upgrading.

**Comment by dbanks91** [comment]
> I don't think this what the card was referring to, it is the actual actions themselves built on Node 16 which are being deprecated. So long as we're using all the action versions listed as running on Node 20, we're fine as far as the actions go.
> 
> Since Node 16 is EOL, we do need to look at upgrading everywhere we use it in our code, but I think that's a bigger job outside the scope of this ticket, and until we've done that we should keep the Node version we run the checks with at 16 hear, since that's what we're currently actually building with. I will add a card to look at the wider job of upgrading.

I think the purpose of the card was to upgrade every repo to use the latest GitHub actions - I'm happy to approve these PRs for now, we could raise another card to do all of them, but I'm concerned about when github might drop support for Node 16 as it could be any moment.

**Review by dbanks91 — APPROVED** [review]

**Comment by kacperpONS** [comment]
@AdamHawtin @dbanks91 
I'll close this PR and leave that to be updated together with the Node version we use for the app

**Comment by kacperpONS** [comment]
@AdamHawtin @dbanks91
I'll close this PR and leave that to be updated together with the Node version we use for the app

**Pull request closed without merging**
